import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { GluestackUIProvider } from "components";
import "./globals.css";
import StyledJsxRegistry from "./registry";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                style={{ flex: 1 }}
            >
                <StyledJsxRegistry>
                    <GluestackUIProvider>
                        <SafeAreaProvider className={` flex-1 overflow-hidden`}>
                            <div className="h-screen w-screen overflow-hidden overflow-y-scroll">
                                {children}
                            </div>
                        </SafeAreaProvider>
                    </GluestackUIProvider>
                </StyledJsxRegistry>
            </body>
        </html>
    );
}
