title: "[Idea]: "
labels: ["idea", "discussion"]
body: |
  ## 💡 Idea
  <!-- Briefly describe your idea -->

  ## Problem/Opportunity
  <!-- What problem does this solve or what opportunity does it create? -->

  ## Proposal
  <!-- Describe your proposed solution or approach -->

  ## Benefits
  <!-- What are the potential benefits? -->

  -
  -
  -

  ## Considerations
  <!-- What should we think about? Trade-offs? -->

  -
  -
  -

  ## Open Questions
  <!-- What needs to be discussed or decided? -->

  1.
  2.
  3.

  ## Additional Context
  <!-- Any other information, examples, or references -->
