title: "[Showcase]: "
labels: ["showcase", "community"]
body: |
  ## 🎨 What did you build?
  <!-- Describe what you created with this project -->

  ## Screenshots/Demo
  <!-- Show us what you made! -->

  ## Description
  <!-- Tell us about your project -->

  - **Purpose**:
  - **Tech Stack**:
  - **Packages Used**:
  - **Highlights**:

  ## Challenges & Solutions
  <!-- What challenges did you face and how did you solve them? -->

  -
  -

  ## Learning & Insights
  <!-- What did you learn? Any insights to share? -->

  -
  -

  ## Links
  <!-- Share your project (if public) -->

  - **Live Demo**:
  - **Repository**:
  - **Blog Post**:

  ## Feedback for the Project
  <!-- Any suggestions or feedback based on your experience? -->

  ---
  Thank you for sharing your work! 🎉
