name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: affected-apps
    attributes:
      label: Affected Apps/Packages
      description: Which parts of the monorepo are affected?
      multiple: true
      options:
        - apps/web (Next.js)
        - apps/mobile (Expo)
        - apps/api (Fastify)
        - packages/components
        - packages/ui
        - packages/database
        - packages/errors
        - packages/service-contracts
        - packages/utils
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Platform(s)
      description: On which platform(s) does this occur?
      multiple: true
      options:
        - Web (Browser)
        - iOS
        - Android
        - API/Backend
        - All platforms
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g. macOS 14.0, Ubuntu 22.04]
        - Node.js version: [e.g. 18.17.0]
        - pnpm version: [e.g. 9.0.0]
        - Browser: [e.g. Chrome 120, Safari 17] (if web)
        - Device: [e.g. iPhone 15, Pixel 7] (if mobile)
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, paste any relevant error logs or console output
      placeholder: Paste logs here...
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain the problem
      placeholder: Drag and drop images/videos here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I am willing to submit a PR to fix this issue (optional)
          required: false
